name: build-skia-3
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "args.gn"
defaults:
  run:
    shell: nu {0}

env:
  SkiaSharpVersion: 3.119.0
jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install LLVM 21
        run: winget install --id LLVM.LLVM --accept-package-agreements --accept-source-agreements --disable-interactivity
      - uses: ./.github/actions/build
      - uses: ./.github/actions/deploy
